#!/bin/sh

libpng_initialize()
{
  typeset _v
  _v=$package_version
  _v=${_v%.*}
  _v=${_v/./}

  package define \
    base_url "http://downloads.sourceforge.net/project/libpng/libpng${_v}/$package_version"
}
